### ISSUE TITLE
Libspotify finally stopped working

### ISSUE THREAD

**Issue by janui** [mopidy/libspotify-archive#1]
Hi there,
I know that you are not an official maintaner of libspotify, but still...
In May 2018 I received an email from Spotify announcing their new improved user interface. spop (which uses libspotif) stopped working almost immediately. spop still logs in correctly but no longer returns anything useful to play.
Looks like the already in 2015 depreciated libspotify has final stopped working.
Are there any plans to re-engineer libspotify to use librespot?
janui

**Comment by kingosticks** [comment]
Since at least one person has managed to find this post I guess it's worth clarifying that libspotify still provides working playback and track lookup. It no longer provides playlists data or search results. 

We have no current plans to make a libspotify compatible wrapper around librespot.
